name: Test and Build code

on:
  pull_request:
    branches: [ develop ]

jobs:
    client-unit-tests:
        runs-on: ubuntu-latest
        steps:
            - run: cd mediamarktClient
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: npm install
            - name: Run unit tests
              run: npm run test